plugins {
    id 'com.android.application'
}

android {
    namespace 'com.whydrive.buildkeeper'
    compileSdk 35

    defaultConfig {
        applicationId "com.whydrive.buildkeeper"
        minSdk 26
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
